name: Triggered Workflow with various Inputs

on:
    workflow_dispatch: 
        inputs:
            run-tests:
                description: "Run the Tests ?"
                type: boolean
                required: true
            test-type:
                description: "Type of tests to run"
                type: choice
                options:
                    - unit
                    - Integration
                    - all
                required: true
            environment:
                description: "Choose an environment"
                required: true
                type: environment          
            build-number:
                description: "Custom Build Number"
                type: number
                required: false
            message:
                description: "Additional message"
                type: string
                required: false

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print workflow inputs
              run: |
                echo "Run tests: ${{ inputs.run-tests }}"
                echo "Test type: ${{ inputs.test-type }}"
                echo "Environment: ${{ inputs.environment }}"
                echo "Build Number: ${{ inputs.build-number }}"
                echo "Message: ${{ inputs.message }}"

            - name: Run test (if selected)
              if: ${{ inputs.run-tests == 'true' }}
              run: echo "Testing................"

            
        

